name: ConnectMTA Debug 

on:
  push:
    paths:
      - '**/*'

jobs:
  build_debug_apk:
    name: Build ConnectMTA APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      # Limpa o cache para garantir que todas as dependências sejam atualizadas
     # - name: Clean old Gradle cache
     #   run: ./gradlew clean --refresh-dependencies

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # Construção com Gradle, baixando todas as dependências necessárias
      - name: Build with Gradle and download dependencies
        id: gradle_build_debug
        run: ./gradlew assembleDebug --refresh-dependencies

      # Upload do APK para file.io
      - name: Upload APK to file.io
        id: upload_apk
        run: |
          apk_path=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          response=$(curl -F "file=@$apk_path" https://file.io)
          echo "Response: $response"
